Complete Level 3 - 4 and Add Lost Field "TankCapacity" To Vehicle
UNDogMan/Pre-DevIncubator pull request #2
Opened 2021-03-13 16:22 UTC by UNDogMan

2021-03-13 17:13 UTC, PushMeNow requested changes
Hi!
I did some comments. Let me know if any comments

2021-03-13 17:13 UTC, PushMeNow commented on Pre-DevIncubator/Models/Engine/AbstractEngine.cs
> +        public double TaxCoefficient { get; set; }
Why TaxCoefficient doesn't have init keyword but Model has?

2021-03-13 17:13 UTC, PushMeNow commented on Pre-DevIncubator/Models/Engine/DieselEngine.cs
> +            :base("Diesel", 1.2)
Space between ':' and 'base'

2021-03-13 17:13 UTC, PushMeNow commented on Pre-DevIncubator/Models/Engine/ElectricalEngine.cs
> +            base("Electrical", 0.1)
Could you configure your IDE formatter correctly? Why is there not space before ':' ?

2021-03-13 17:13 UTC, PushMeNow commented on Pre-DevIncubator/Models/Engine/ElectricalEngine.cs
> +        public double ElectricityConsumption { get; init; }
Again I don't realize why here init keyword

2021-03-13 17:13 UTC, PushMeNow commented on Pre-DevIncubator/Models/Vehicle.cs
> +        public double TankCapacity { get; set; }
init?

2021-03-15 19:37 UTC, PushMeNow approved these changes
Looks good! Approve.

2021-03-17 14:09 UTC, dbogdan2000 approved these changes

2021-03-17 14:49 UTC, ArtyomKolosov2 approved these changes

2021-03-17 14:49 UTC, merged